// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3mzPHnv45VnKxIuAR_UjI55tCJy9MHls',
    appId: '1:408422289674:web:a5122e7b10ab5170b72af3',
    messagingSenderId: '408422289674',
    projectId: 'lab8-4763f',
    authDomain: 'lab8-4763f.firebaseapp.com',
    databaseURL: 'https://lab8-4763f-default-rtdb.firebaseio.com',
    storageBucket: 'lab8-4763f.firebasestorage.app',
    measurementId: 'G-HZ9L3GMB7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAevKmnLWjD_6MZ2Zw9Oyh4BR0XkuYrvSM',
    appId: '1:408422289674:android:eae6f33a79fcf912b72af3',
    messagingSenderId: '408422289674',
    projectId: 'lab8-4763f',
    databaseURL: 'https://lab8-4763f-default-rtdb.firebaseio.com',
    storageBucket: 'lab8-4763f.firebasestorage.app',
  );
}
